# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: CHERI-Zephyr
email: "me@example.com" # FIXME
description: >- # this means to ignore newlines until "baseurl:"
  A high level overview of the CHERI-Zephyr Project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com #FIXME

permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
repo: "https://github.com/cheri-zephyr-project/project_website"
sass:
  style: compressed # Style compression
  quiet_deps: true

# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "The CHERI-Zephyr Project" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Build settings
theme: alembic-jekyll-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
exclude:
  - .jekyll-cache
  - .sass-cache/
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages


# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Blog
  url: /blog/
- title: Use Cases
  url: /use_cases
- title: Getting Started
  url: /getting_started
- title: Contact
  url: /contact
#- title: Search
#  url: /search/
- title: Project Github
  url: https://github.com/cheri-zephyr-project

navigation_footer:
- title: CHERI-Zephyr Group
  url: https://cheri-zephyr-project.github.io/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/cheri-zephyr-project
  link: https://cheri-zephyr-project.github.io/
  RSS: /feed.xml
